HAI 1.2
    I HAS A NUM ITZ A NUMBR
    I HAS A SUMDIG ITZ 0
    GIMMEH NUM
    IM IN YR LOOP UPPIN YR VAR TIL BOTH SAEM NUM AN 0
        SUMDIG R SUM OF SUMDIG AN MOD OF NUM AN 10
        NUM R QUOSHUNT OF NUM AN 10
    IM OUTTA YR LOOP
    VISIBLE SUMDIG
KTHXBYE