HAI 1.2
    I HAS A COORD ITZ A BUKKIT
    COORD HAS A X ITZ A NUMBAR
    COORD HAS A V ITZ A NUMBAR
    I HAS A COORD2 ITZ A BUKKIT
    COORD2 HAS A X ITZ A NUMBAR
    COORD2 HAS A V ITZ A NUMBAR
    VISIBLE "ENTER COORDINATES OF PT1: "
    GIMMEH COORD'Z X, GIMMEH COORD'Z Y
    VISIBLE "ENTER COORDINATES OF PT2: "
    GIMMEH COORD2'Z X, GIMMEH COORD2'Z Y
    I HAS A DIST ITZ A NUMBAR
KTHXBYE
    