HAI 1.2
    I HAS A VAR ITZ A NUMBR
    I HAS A TOT ITZ 0
    GIMMEH VAR
    VAR R MAEK VAR A NUMBR
    IM IN YR LOOP UPPIN YR VA TIL BOTH SAEM SUM OF VAR AN 1 AN VA
        TOT R SUM OF TOT AN VA
    IM OUTTA YR LOOP
    VISIBLE TOT
KTHXBYE