HAI 1.2
    I HAS A SEC ITZ A NUMBR
    I HAS A MIN ITZ A NUMBR
    I HAS A HOUR ITZ A NUMBR
    VISIBLE "ENTER TIME IN SECONDS:"
    GIMMEH SEC
    MIN R QUOSHUNT OF SEC AN 60
    SEC R MOD OF SEC AN 60
    HOUR R QUOSHUNT OF MIN AN 60
    MIN R MOD OF MIN AN 60
    VISIBLE SMOOSH HOUR "HRS " MIN "MINS " SEC "SECS " MKAY
KTHXBYE
